import React from "react";
import './portfolio.css';
import carousel from '../../assest/3D carousel.jpg';
import book from '../../assest/book lib.jpg';
import password from '../../assest/password g.jpg';
import netflix from '../../assest/Netflix.jpg';
import youtube from '../../assest/youtube.jpg';

const data=[
    {
        id:1,
        image:carousel,
        title:"3D carousel",
        github:'https://github.com/Shudhanshusoni/3d-carousel-github.io',
        demo:'https://shudhanshusoni.github.io/3d-carousel-github.io/',
        review:"Created a website user can see my all mini project in carousel effect and on click on image can go to the hosting website of projects."
    },
    {
        id:2,
        image:book,
        title:"Book Library",
        github:'https://github.com/Shudhanshusoni/book-app-shudhanshu',
        demo:'https://soni-booklibrary.netlify.app/',
        review:"Created a website where users can search for any book without click enter and on click on book can read the authors name ,published date and intro page and can read and buy book through google Ebook "
    },
    {
        id:3,
        image:password,
        title:"Password Generator",
        github:'https://github.com/Shudhanshusoni/password-generator-shudhanshu.github.io',
        demo:'https://shudhanshusoni.github.io/password-generator-shudhanshu.github.io/',
        review:"Created a website where users can generate random by selecting combination of upper,lower ,number and special character."

    },
    {
        id:4,
        image:netflix,
        title:"Netflix ui clone",
        github:'https://github.com/Shudhanshusoni/Netflix-clone-shudhanshu.github.io',
        demo:'https://netflix-carousel-clone.netlify.app',
        review:"Created a clone Ui of home page of netflix focusing on 3D Carousel effect"
    },
    {
        id:5,
        image:youtube,
        title:"Youtube clone",
        github:'https://github.com/Shudhanshusoni/youtube-clone-by-shudhanshu',
        demo:'https://shudhanshusoni.github.io/youtube-clone-by-shudhanshu/',
        review:"Created a website where users can search for any videos and can watch it.I have used ES6 to fetch youtube api which was generated by me on free api source."
    }
]

const Portfolio=()=>{
    return(
        <section id="portfolio">
        <h5>My Recent Work</h5> 
        <h2>Portfolio</h2>

        <div className="container portfolio_container">
       {
        data.map((
            {id,image,title,github,demo,review}
        )=>{
            return(
            <article key={id} className="portfolio_item ">
            
            
            <div className="item_image project-card-hover">
                <img src={image} alt={title}/>
                <div class="layer">
             <div class="project-info">
              <h3>
               { review}
              </h3>
              </div>
              </div>
            </div>
            
            <h3>{title}</h3>
            <div className="item_cta">
            <a href={github} className="btn" target='_blank'>GitHub</a>
            <a href={demo} className="btn btn-primary" target='_blank'>Live Demo</a>
            </div>
            </article>
            )
        })
       }
       
        </div>
        </section>
    )
    
}
export default Portfolio;